export interface Country {
  name: CountryName;
  code: string;
  phoneCode: string;
}

export enum CountryName {
  Afganistan = 'Afganistán',
  Albania = 'Albania',
  Alemania = 'Alemania',
  Andorra = 'Andorra',
  Angola = 'Angola',
  Anguila = 'Anguila',
  Antartida = 'Antártida',
  AntiguaYBarbuda = 'Antigua y Barbuda',
  AntillasHolandesas = 'Antillas Holandesas',
  ArabiaSaudita = 'Arabia Saudita',
  Argelia = 'Argelia',
  Argentina = 'Argentina',
  Armenia = 'Armenia',
  Aruba = 'Aruba',
  Australia = 'Australia',
  Austria = 'Austria',
  Azerbaiyan = 'Azerbaiyán',
  Bahamas = 'Bahamas',
  Bahrein = 'Bahrein',
  Bangladesh = 'Bangladesh',
  Barbados = 'Barbados',
  Belgica = 'Bélgica',
  Belice = 'Belice',
  Benin = 'Benín',
  Bhutan = 'Bhután',
  Bielorrusia = 'Bielorrusia',
  Birmania = 'Birmania',
  Bolivia = 'Bolivia',
  BosniaYHerzegovina = 'Bosnia y Herzegovina',
  Botsuana = 'Botsuana',
  Brasil = 'Brasil',
  Brunei = 'Brunéi',
  Bulgaria = 'Bulgaria',
  BurkinaFaso = 'Burkina Faso',
  Burundi = 'Burundi',
  CaboVerde = 'Cabo Verde',
  Camboya = 'Camboya',
  Camerun = 'Camerún',
  Canada = 'Canadá',
  Chad = 'Chad',
  Chile = 'Chile',
  China = 'China',
  Chipre = 'Chipre',
  CiudadDelVaticano = 'Ciudad del Vaticano',
  Colombia = 'Colombia',
  Comoras = 'Comoras',
  CoreaDelNorte = 'Corea del Norte',
  CoreaDelSur = 'Corea del Sur',
  CostaDeMarfil = 'Costa de Marfil',
  CostaRica = 'Costa Rica',
  Croacia = 'Croacia',
  Cuba = 'Cuba',
  Dinamarca = 'Dinamarca',
  Dominica = 'Dominica',
  Ecuador = 'Ecuador',
  Egipto = 'Egipto',
  ElSalvador = 'El Salvador',
  EmiratosArabesUnidos = 'Emiratos Árabes Unidos',
  Eritrea = 'Eritrea',
  Eslovaquia = 'Eslovaquia',
  Eslovenia = 'Eslovenia',
  Espana = 'España',
  EstadosUnidosDeAmerica = 'Estados Unidos de América',
  Estonia = 'Estonia',
  Etiopia = 'Etiopía',
  Filipinas = 'Filipinas',
  Finlandia = 'Finlandia',
  Fiyi = 'Fiyi',
  Francia = 'Francia',
  Gabon = 'Gabón',
  Gambia = 'Gambia',
  Georgia = 'Georgia',
  Ghana = 'Ghana',
  Gibraltar = 'Gibraltar',
  Granada = 'Granada',
  Grecia = 'Grecia',
  Groenlandia = 'Groenlandia',
  Guadalupe = 'Guadalupe',
  Guam = 'Guam',
  Guatemala = 'Guatemala',
  GuayanaFrancesa = 'Guayana Francesa',
  Guernsey = 'Guernsey',
  Guinea = 'Guinea',
  GuineaEcuatorial = 'Guinea Ecuatorial',
  GuineaBissau = 'Guinea-Bissau',
  Guyana = 'Guyana',
  Haiti = 'Haití',
  Honduras = 'Honduras',
  HongKong = 'Hong kong',
  Hungria = 'Hungría',
  India = 'India',
  Indonesia = 'Indonesia',
  Irak = 'Irak',
  Iran = 'Irán',
  Irlanda = 'Irlanda',
  IslaDeMan = 'Isla de Man',
  IslaDeNavidad = 'Isla de Navidad',
  IslaNorfolk = 'Isla Norfolk',
  Islandia = 'Islandia',
  IslasBermudas = 'Islas Bermudas',
  IslasCaiman = 'Islas Caimán',
  IslasCocosKeeling = 'Islas Cocos (Keeling)',
  IslasDeAland = 'Islas de Åland',
  IslasFeroe = 'Islas Feroe',
  IslasGeorgiasDelSurYSandwichDelSur = 'Islas Georgias del Sur y Sandwich del Sur',
  IslasMaldivas = 'Islas Maldivas',
  IslasMalvinas = 'Islas Malvinas',
  IslasMarianasDelNorte = 'Islas Marianas del Norte',
  IslasMarshall = 'Islas Marshall',
  IslasPitcairn = 'Islas Pitcairn',
  IslasSalomon = 'Islas Salomón',
  IslasTurcasYCaicos = 'Islas Turcas y Caicos',
  IslasVirgenesBritanicas = 'Islas Vírgenes Británicas',
  IslasVirgenesDeLosEstadosUnidos = 'Islas Vírgenes de los Estados Unidos',
  Israel = 'Israel',
  Italia = 'Italia',
  Jamaica = 'Jamaica',
  Japon = 'Japón',
  Jersey = 'Jersey',
  Jordania = 'Jordania',
  Kazajistan = 'Kazajistán',
  Kenia = 'Kenia',
  Kirguistan = 'Kirguistán',
  Kiribati = 'Kiribati',
  Kuwait = 'Kuwait',
  Laos = 'Laos',
  Lesoto = 'Lesoto',
  Letonia = 'Letonia',
  Libano = 'Líbano',
  Liberia = 'Liberia',
  Libia = 'Libia',
  Liechtenstein = 'Liechtenstein',
  Lituania = 'Lituania',
  Luxemburgo = 'Luxemburgo',
  Macao = 'Macao',
  MacedoniaDelNorte = 'Macedonia del Norte',
  Madagascar = 'Madagascar',
  Malasia = 'Malasia',
  Malawi = 'Malawi',
  Mali = 'Mali',
  Malta = 'Malta',
  Marruecos = 'Marruecos',
  Martinica = 'Martinica',
  Mauricio = 'Mauricio',
  Mauritania = 'Mauritania',
  Mayotte = 'Mayotte',
  Mexico = 'México',
  Micronesia = 'Micronesia',
  Moldavia = 'Moldavia',
  Monaco = 'Mónaco',
  Mongolia = 'Mongolia',
  Montenegro = 'Montenegro',
  Montserrat = 'Montserrat',
  Mozambique = 'Mozambique',
  Namibia = 'Namibia',
  Nauru = 'Nauru',
  Nepal = 'Nepal',
  Nicaragua = 'Nicaragua',
  Niger = 'Niger',
  Nigeria = 'Nigeria',
  Niue = 'Niue',
  Noruega = 'Noruega',
  NuevaCaledonia = 'Nueva Caledonia',
  NuevaZelanda = 'Nueva Zelanda',
  Oman = 'Omán',
  PaisesBajos = 'Países Bajos',
  Pakistan = 'Pakistán',
  Palau = 'Palau',
  Palestina = 'Palestina',
  Panama = 'Panamá',
  PapuaNuevaGuinea = 'Papúa Nueva Guinea',
  Paraguay = 'Paraguay',
  Peru = 'Perú',
  PolinesiaFrancesa = 'Polinesia Francesa',
  Polonia = 'Polonia',
  Portugal = 'Portugal',
  PuertoRico = 'Puerto Rico',
  Qatar = 'Qatar',
  ReinoUnido = 'Reino Unido',
  RepublicaCentroafricana = 'República Centroafricana',
  RepublicaCheca = 'República Checa',
  RepublicaSudanDelSur = 'República de Sudán del Sur',
  RepublicaDelCongo = 'República del Congo',
  RepublicaDemocraticaDelCongo = 'República Democrática del Congo',
  RepublicaDominicana = 'República Dominicana',
  Reunion = 'Reunión',
  Ruanda = 'Ruanda',
  Rumania = 'Rumanía',
  Rusia = 'Rusia',
  Samoa = 'Samoa',
  SamoaAmericana = 'Samoa Americana',
  SanBartolome = 'San Bartolomé',
  SanCristobalYNieves = 'San Cristóbal y Nieves',
  SanMarino = 'San Marino',
  SanMartinFrancia = 'San Martín (Francia)',
  SanPedroYMiquelon = 'San Pedro y Miquelón',
  SanVicenteYLasGranadinas = 'San Vicente y las Granadinas',
  SantaElena = 'Santa Elena',
  SantaLucia = 'Santa Lucía',
  SantoTomeYPrincipe = 'Santo Tomé y Príncipe',
  Senegal = 'Senegal',
  Serbia = 'Serbia',
  Seychelles = 'Seychelles',
  SierraLeona = 'Sierra Leona',
  Singapur = 'Singapur',
  Siria = 'Siria',
  Somalia = 'Somalia',
  SriLanka = 'Sri lanka',
  Sudafrica = 'Sudáfrica',
  Sudan = 'Sudán',
  Suecia = 'Suecia',
  Suiza = 'Suiza',
  Surinam = 'Surinám',
  SvalbardYJanMayen = 'Svalbard y Jan Mayen',
  Swazilandia = 'Swazilandia',
  Tailandia = 'Tailandia',
  Taiwan = 'Taiwán',
  Tanzania = 'Tanzania',
  Tayikistan = 'Tayikistán',
  TerritorioBritanicoDelOceanoIndico = 'Territorio Británico del Océano Índico',
  TimorOriental = 'Timor Oriental',
  Togo = 'Togo',
  Tokelau = 'Tokelau',
  Tonga = 'Tonga',
  TrinidadYTobago = 'Trinidad y Tobago',
  Tunez = 'Tunez',
  Turkmenistan = 'Turkmenistán',
  Turquia = 'Turquía',
  Tuvalu = 'Tuvalu',
  Ucrania = 'Ucrania',
  Uganda = 'Uganda',
  Uruguay = 'Uruguay',
  Uzbekistan = 'Uzbekistán',
  Vanuatu = 'Vanuatu',
  Venezuela = 'Venezuela',
  Vietnam = 'Vietnam',
  WallisYFutuna = 'Wallis y Futuna',
  Yemen = 'Yemen',
  Yibuti = 'Yibuti',
  Zambia = 'Zambia',
  Zimbabue = 'Zimbabue',
}

export const countries: Country[] = [
  {
    name: CountryName.Afganistan,
    code: 'AF',
    phoneCode: '+93',
  },
  {
    name: CountryName.Albania,
    code: 'AL',
    phoneCode: '+355',
  },
  {
    name: CountryName.Alemania,
    code: 'DE',
    phoneCode: '+49',
  },
  {
    name: CountryName.Andorra,
    code: 'AD',
    phoneCode: '+376',
  },
  {
    name: CountryName.Angola,
    code: 'AO',
    phoneCode: '+244',
  },
  {
    name: CountryName.Anguila,
    code: 'AI',
    phoneCode: '+1264',
  },
  {
    name: CountryName.Antartida,
    code: 'AQ',
    phoneCode: '+672',
  },
  {
    name: CountryName.AntiguaYBarbuda,
    code: 'AG',
    phoneCode: '+1268',
  },
  {
    name: CountryName.AntillasHolandesas,
    code: 'AN',
    phoneCode: '+599',
  },
  {
    name: CountryName.ArabiaSaudita,
    code: 'SA',
    phoneCode: '+966',
  },
  {
    name: CountryName.Argelia,
    code: 'DZ',
    phoneCode: '+213',
  },
  {
    name: CountryName.Argentina,
    code: 'AR',
    phoneCode: '+54',
  },
  {
    name: CountryName.Armenia,
    code: 'AM',
    phoneCode: '+374',
  },
  {
    name: CountryName.Aruba,
    code: 'AW',
    phoneCode: '+297',
  },
  {
    name: CountryName.Australia,
    code: 'AU',
    phoneCode: '+61',
  },
  {
    name: CountryName.Austria,
    code: 'AT',
    phoneCode: '+43',
  },
  {
    name: CountryName.Azerbaiyan,
    code: 'AZ',
    phoneCode: '+994',
  },
  {
    name: CountryName.Bahamas,
    code: 'BS',
    phoneCode: '+1242',
  },
  {
    name: CountryName.Bahrein,
    code: 'BH',
    phoneCode: '+973',
  },
  {
    name: CountryName.Bangladesh,
    code: 'BD',
    phoneCode: '+880',
  },
  {
    name: CountryName.Barbados,
    code: 'BB',
    phoneCode: '+1246',
  },
  {
    name: CountryName.Belgica,
    code: 'BE',
    phoneCode: '+32',
  },
  {
    name: CountryName.Belice,
    code: 'BZ',
    phoneCode: '+501',
  },
  {
    name: CountryName.Benin,
    code: 'BJ',
    phoneCode: '+229',
  },
  {
    name: CountryName.Bhutan,
    code: 'BT',
    phoneCode: '+975',
  },
  {
    name: CountryName.Bielorrusia,
    code: 'BY',
    phoneCode: '+375',
  },
  {
    name: CountryName.Birmania,
    code: 'MM',
    phoneCode: '+95',
  },
  {
    name: CountryName.Bolivia,
    code: 'BO',
    phoneCode: '+591',
  },
  {
    name: CountryName.BosniaYHerzegovina,
    code: 'BA',
    phoneCode: '+387',
  },
  {
    name: CountryName.Botsuana,
    code: 'BW',
    phoneCode: '+267',
  },
  {
    name: CountryName.Brasil,
    code: 'BR',
    phoneCode: '+55',
  },
  {
    name: CountryName.Brunei,
    code: 'BN',
    phoneCode: '+673',
  },
  {
    name: CountryName.Bulgaria,
    code: 'BG',
    phoneCode: '+359',
  },
  {
    name: CountryName.BurkinaFaso,
    code: 'BF',
    phoneCode: '+226',
  },
  {
    name: CountryName.Burundi,
    code: 'BI',
    phoneCode: '+257',
  },
  {
    name: CountryName.CaboVerde,
    code: 'CV',
    phoneCode: '+238',
  },
  {
    name: CountryName.Camboya,
    code: 'KH',
    phoneCode: '+855',
  },
  {
    name: CountryName.Camerun,
    code: 'CM',
    phoneCode: '+237',
  },
  {
    name: CountryName.Canada,
    code: 'CA',
    phoneCode: '+1',
  },
  {
    name: CountryName.Chad,
    code: 'TD',
    phoneCode: '+235',
  },
  {
    name: CountryName.Chile,
    code: 'CL',
    phoneCode: '+56',
  },
  {
    name: CountryName.China,
    code: 'CN',
    phoneCode: '+86',
  },
  {
    name: CountryName.Chipre,
    code: 'CY',
    phoneCode: '+357',
  },
  {
    name: CountryName.CiudadDelVaticano,
    code: 'VA',
    phoneCode: '+379',
  },
  {
    name: CountryName.Colombia,
    code: 'CO',
    phoneCode: '+57',
  },
  {
    name: CountryName.Comoras,
    code: 'KM',
    phoneCode: '+269',
  },
  {
    name: CountryName.CoreaDelNorte,
    code: 'KP',
    phoneCode: '+850',
  },
  {
    name: CountryName.CoreaDelSur,
    code: 'KR',
    phoneCode: '+82',
  },
  {
    name: CountryName.CostaDeMarfil,
    code: 'CI',
    phoneCode: '+225',
  },
  {
    name: CountryName.CostaRica,
    code: 'CR',
    phoneCode: '+506',
  },
  {
    name: CountryName.Croacia,
    code: 'HR',
    phoneCode: '+385',
  },
  {
    name: CountryName.Cuba,
    code: 'CU',
    phoneCode: '+53',
  },
  {
    name: CountryName.Dinamarca,
    code: 'DK',
    phoneCode: '+45',
  },
  {
    name: CountryName.Dominica,
    code: 'DM',
    phoneCode: '+1767',
  },
  {
    name: CountryName.Ecuador,
    code: 'EC',
    phoneCode: '+593',
  },
  {
    name: CountryName.Egipto,
    code: 'EG',
    phoneCode: '+20',
  },
  {
    name: CountryName.ElSalvador,
    code: 'SV',
    phoneCode: '+503',
  },
  {
    name: CountryName.EmiratosArabesUnidos,
    code: 'AE',
    phoneCode: '+971',
  },
  {
    name: CountryName.Eritrea,
    code: 'ER',
    phoneCode: '+291',
  },
  {
    name: CountryName.Eslovaquia,
    code: 'SK',
    phoneCode: '+421',
  },
  {
    name: CountryName.Eslovenia,
    code: 'SI',
    phoneCode: '+386',
  },
  {
    name: CountryName.Espana,
    code: 'ES',
    phoneCode: '+34',
  },
  {
    name: CountryName.EstadosUnidosDeAmerica,
    code: 'US',
    phoneCode: '+1',
  },
  {
    name: CountryName.Estonia,
    code: 'EE',
    phoneCode: '+372',
  },
  {
    name: CountryName.Etiopia,
    code: 'ET',
    phoneCode: '+251',
  },
  {
    name: CountryName.Filipinas,
    code: 'PH',
    phoneCode: '+63',
  },
  {
    name: CountryName.Finlandia,
    code: 'FI',
    phoneCode: '+358',
  },
  {
    name: CountryName.Fiyi,
    code: 'FJ',
    phoneCode: '+679',
  },
  {
    name: CountryName.Francia,
    code: 'FR',
    phoneCode: '+33',
  },
  {
    name: CountryName.Gabon,
    code: 'GA',
    phoneCode: '+241',
  },
  {
    name: CountryName.Gambia,
    code: 'GM',
    phoneCode: '+220',
  },
  {
    name: CountryName.Georgia,
    code: 'GE',
    phoneCode: '+995',
  },
  {
    name: CountryName.Ghana,
    code: 'GH',
    phoneCode: '+233',
  },
  {
    name: CountryName.Gibraltar,
    code: 'GI',
    phoneCode: '+350',
  },
  {
    name: CountryName.Granada,
    code: 'GD',
    phoneCode: '+1473',
  },
  {
    name: CountryName.Grecia,
    code: 'GR',
    phoneCode: '+30',
  },
  {
    name: CountryName.Groenlandia,
    code: 'GL',
    phoneCode: '+299',
  },
  {
    name: CountryName.Guadalupe,
    code: 'GP',
    phoneCode: '+590',
  },
  {
    name: CountryName.Guam,
    code: 'GU',
    phoneCode: '+1671',
  },
  {
    name: CountryName.Guatemala,
    code: 'GT',
    phoneCode: '+502',
  },
  {
    name: CountryName.GuayanaFrancesa,
    code: 'GF',
    phoneCode: '+594',
  },
  {
    name: CountryName.Guernsey,
    code: 'GG',
    phoneCode: '+44',
  },
  {
    name: CountryName.Guinea,
    code: 'GN',
    phoneCode: '+224',
  },
  {
    name: CountryName.GuineaEcuatorial,
    code: 'GQ',
    phoneCode: '+240',
  },
  {
    name: CountryName.GuineaBissau,
    code: 'GW',
    phoneCode: '+245',
  },
  {
    name: CountryName.Guyana,
    code: 'GY',
    phoneCode: '+595',
  },
  {
    name: CountryName.Haiti,
    code: 'HT',
    phoneCode: '+509',
  },
  {
    name: CountryName.Honduras,
    code: 'HN',
    phoneCode: '+504',
  },
  {
    name: CountryName.HongKong,
    code: 'HK',
    phoneCode: '+852',
  },
  {
    name: CountryName.Hungria,
    code: 'HU',
    phoneCode: '+36',
  },
  {
    name: CountryName.India,
    code: 'IN',
    phoneCode: '+91',
  },
  {
    name: CountryName.Indonesia,
    code: 'ID',
    phoneCode: '+62',
  },
  {
    name: CountryName.Irak,
    code: 'IQ',
    phoneCode: '+964',
  },
  {
    name: CountryName.Iran,
    code: 'IR',
    phoneCode: '+98',
  },
  {
    name: CountryName.Irlanda,
    code: 'IE',
    phoneCode: '+353',
  },
  {
    name: CountryName.IslaDeMan,
    code: 'IM',
    phoneCode: '+44',
  },
  {
    name: CountryName.IslaDeNavidad,
    code: 'CX',
    phoneCode: '+61',
  },
  {
    name: CountryName.IslaNorfolk,
    code: 'NF',
    phoneCode: '+672',
  },
  {
    name: CountryName.Islandia,
    code: 'IS',
    phoneCode: '+354',
  },
  {
    name: CountryName.IslasBermudas,
    code: 'BM',
    phoneCode: '+1441',
  },
  {
    name: CountryName.IslasCaiman,
    code: 'KY',
    phoneCode: '+345',
  },
  {
    name: CountryName.IslasCocosKeeling,
    code: 'CC',
    phoneCode: '+61',
  },
  {
    name: CountryName.IslasDeAland,
    code: 'AX',
    phoneCode: '+358',
  },
  {
    name: CountryName.IslasFeroe,
    code: 'FO',
    phoneCode: '+298',
  },
  {
    name: CountryName.IslasGeorgiasDelSurYSandwichDelSur,
    code: 'GS',
    phoneCode: '+500',
  },
  {
    name: CountryName.IslasMaldivas,
    code: 'MV',
    phoneCode: '+960',
  },
  {
    name: CountryName.IslasMalvinas,
    code: 'FK',
    phoneCode: '+500',
  },
  {
    name: CountryName.IslasMarianasDelNorte,
    code: 'MP',
    phoneCode: '+1670',
  },
  {
    name: CountryName.IslasMarshall,
    code: 'MH',
    phoneCode: '+692',
  },
  {
    name: CountryName.IslasPitcairn,
    code: 'PN',
    phoneCode: '+872',
  },
  {
    name: CountryName.IslasSalomon,
    code: 'SB',
    phoneCode: '+677',
  },
  {
    name: CountryName.IslasTurcasYCaicos,
    code: 'TC',
    phoneCode: '+1649',
  },
  {
    name: CountryName.IslasVirgenesBritanicas,
    code: 'VG',
    phoneCode: '+1284',
  },
  {
    name: CountryName.IslasVirgenesDeLosEstadosUnidos,
    code: 'VI',
    phoneCode: '+1340',
  },
  {
    name: CountryName.Israel,
    code: 'IL',
    phoneCode: '+972',
  },
  {
    name: CountryName.Italia,
    code: 'IT',
    phoneCode: '+39',
  },
  {
    name: CountryName.Jamaica,
    code: 'JM',
    phoneCode: '+1876',
  },
  {
    name: CountryName.Japon,
    code: 'JP',
    phoneCode: '+81',
  },
  {
    name: CountryName.Jersey,
    code: 'JE',
    phoneCode: '+44',
  },
  {
    name: CountryName.Jordania,
    code: 'JO',
    phoneCode: '+962',
  },
  {
    name: CountryName.Kazajistan,
    code: 'KZ',
    phoneCode: '+77',
  },
  {
    name: CountryName.Kenia,
    code: 'KE',
    phoneCode: '+254',
  },
  {
    name: CountryName.Kirguistan,
    code: 'KG',
    phoneCode: '+996',
  },
  {
    name: CountryName.Kiribati,
    code: 'KI',
    phoneCode: '+686',
  },
  {
    name: CountryName.Kuwait,
    code: 'KW',
    phoneCode: '+965',
  },
  {
    name: CountryName.Laos,
    code: 'LA',
    phoneCode: '+856',
  },
  {
    name: CountryName.Lesoto,
    code: 'LS',
    phoneCode: '+266',
  },
  {
    name: CountryName.Letonia,
    code: 'LV',
    phoneCode: '+371',
  },
  {
    name: CountryName.Libano,
    code: 'LB',
    phoneCode: '+961',
  },
  {
    name: CountryName.Liberia,
    code: 'LR',
    phoneCode: '+231',
  },
  {
    name: CountryName.Libia,
    code: 'LY',
    phoneCode: '+218',
  },
  {
    name: CountryName.Liechtenstein,
    code: 'LI',
    phoneCode: '+423',
  },
  {
    name: CountryName.Lituania,
    code: 'LT',
    phoneCode: '+370',
  },
  {
    name: CountryName.Luxemburgo,
    code: 'LU',
    phoneCode: '+352',
  },
  {
    name: CountryName.Macao,
    code: 'MO',
    phoneCode: '+853',
  },
  {
    name: CountryName.MacedoniaDelNorte,
    code: 'MK',
    phoneCode: '+389',
  },
  {
    name: CountryName.Madagascar,
    code: 'MG',
    phoneCode: '+261',
  },
  {
    name: CountryName.Malasia,
    code: 'MY',
    phoneCode: '+60',
  },
  {
    name: CountryName.Malawi,
    code: 'MW',
    phoneCode: '+265',
  },
  {
    name: CountryName.Mali,
    code: 'ML',
    phoneCode: '+223',
  },
  {
    name: CountryName.Malta,
    code: 'MT',
    phoneCode: '+356',
  },
  {
    name: CountryName.Marruecos,
    code: 'MA',
    phoneCode: '+212',
  },
  {
    name: CountryName.Martinica,
    code: 'MQ',
    phoneCode: '+596',
  },
  {
    name: CountryName.Mauricio,
    code: 'MU',
    phoneCode: '+230',
  },
  {
    name: CountryName.Mauritania,
    code: 'MR',
    phoneCode: '+222',
  },
  {
    name: CountryName.Mayotte,
    code: 'YT',
    phoneCode: '+262',
  },
  {
    name: CountryName.Mexico,
    code: 'MX',
    phoneCode: '+52',
  },
  {
    name: CountryName.Micronesia,
    code: 'FM',
    phoneCode: '+691',
  },
  {
    name: CountryName.Moldavia,
    code: 'MD',
    phoneCode: '+373',
  },
  {
    name: CountryName.Monaco,
    code: 'MC',
    phoneCode: '+377',
  },
  {
    name: CountryName.Mongolia,
    code: 'MN',
    phoneCode: '+976',
  },
  {
    name: CountryName.Montenegro,
    code: 'ME',
    phoneCode: '+382',
  },
  {
    name: CountryName.Montserrat,
    code: 'MS',
    phoneCode: '+1664',
  },
  {
    name: CountryName.Mozambique,
    code: 'MZ',
    phoneCode: '+258',
  },
  {
    name: CountryName.Namibia,
    code: 'NA',
    phoneCode: '+264',
  },
  {
    name: CountryName.Nauru,
    code: 'NR',
    phoneCode: '+674',
  },
  {
    name: CountryName.Nepal,
    code: 'NP',
    phoneCode: '+977',
  },
  {
    name: CountryName.Nicaragua,
    code: 'NI',
    phoneCode: '+505',
  },
  {
    name: CountryName.Niger,
    code: 'NE',
    phoneCode: '+227',
  },
  {
    name: CountryName.Nigeria,
    code: 'NG',
    phoneCode: '+234',
  },
  {
    name: CountryName.Niue,
    code: 'NU',
    phoneCode: '+683',
  },
  {
    name: CountryName.Noruega,
    code: 'NO',
    phoneCode: '+47',
  },
  {
    name: CountryName.NuevaCaledonia,
    code: 'NC',
    phoneCode: '+687',
  },
  {
    name: CountryName.NuevaZelanda,
    code: 'NZ',
    phoneCode: '+64',
  },
  {
    name: CountryName.Oman,
    code: 'OM',
    phoneCode: '+968',
  },
  {
    name: CountryName.PaisesBajos,
    code: 'NL',
    phoneCode: '+31',
  },
  {
    name: CountryName.Pakistan,
    code: 'PK',
    phoneCode: '+92',
  },
  {
    name: CountryName.Palau,
    code: 'PW',
    phoneCode: '+680',
  },
  {
    name: CountryName.Palestina,
    code: 'PS',
    phoneCode: '+970',
  },
  {
    name: CountryName.Panama,
    code: 'PA',
    phoneCode: '+507',
  },
  {
    name: CountryName.PapuaNuevaGuinea,
    code: 'PG',
    phoneCode: '+675',
  },
  {
    name: CountryName.Paraguay,
    code: 'PY',
    phoneCode: '+595',
  },
  {
    name: CountryName.Peru,
    code: 'PE',
    phoneCode: '+51',
  },
  {
    name: CountryName.PolinesiaFrancesa,
    code: 'PF',
    phoneCode: '+689',
  },
  {
    name: CountryName.Polonia,
    code: 'PL',
    phoneCode: '+48',
  },
  {
    name: CountryName.Portugal,
    code: 'PT',
    phoneCode: '+351',
  },
  {
    name: CountryName.PuertoRico,
    code: 'PR',
    phoneCode: '+1939',
  },
  {
    name: CountryName.Qatar,
    code: 'QA',
    phoneCode: '+974',
  },
  {
    name: CountryName.ReinoUnido,
    code: 'GB',
    phoneCode: '+44',
  },
  {
    name: CountryName.RepublicaCentroafricana,
    code: 'CF',
    phoneCode: '+236',
  },
  {
    name: CountryName.RepublicaCheca,
    code: 'CZ',
    phoneCode: '+420',
  },
  {
    name: CountryName.RepublicaSudanDelSur,
    code: 'SS',
    phoneCode: '+211',
  },
  {
    name: CountryName.RepublicaDelCongo,
    code: 'CG',
    phoneCode: '+242',
  },
  {
    name: CountryName.RepublicaDemocraticaDelCongo,
    code: 'CD',
    phoneCode: '+243',
  },
  {
    name: CountryName.RepublicaDominicana,
    code: 'DO',
    phoneCode: '+1849',
  },
  {
    name: CountryName.Reunion,
    code: 'RE',
    phoneCode: '+262',
  },
  {
    name: CountryName.Ruanda,
    code: 'RW',
    phoneCode: '+250',
  },
  {
    name: CountryName.Rumania,
    code: 'RO',
    phoneCode: '+40',
  },
  {
    name: CountryName.Rusia,
    code: 'RU',
    phoneCode: '+7',
  },
  {
    name: CountryName.Samoa,
    code: 'WS',
    phoneCode: '+685',
  },
  {
    name: CountryName.SamoaAmericana,
    code: 'AS',
    phoneCode: '+1684',
  },
  {
    name: CountryName.SanBartolome,
    code: 'BL',
    phoneCode: '+590',
  },
  {
    name: CountryName.SanCristobalYNieves,
    code: 'KN',
    phoneCode: '+1869',
  },
  {
    name: CountryName.SanMarino,
    code: 'SM',
    phoneCode: '+378',
  },
  {
    name: CountryName.SanMartinFrancia,
    code: 'MF',
    phoneCode: '+590',
  },
  {
    name: CountryName.SanPedroYMiquelon,
    code: 'PM',
    phoneCode: '+508',
  },
  {
    name: CountryName.SanVicenteYLasGranadinas,
    code: 'VC',
    phoneCode: '+1784',
  },
  {
    name: CountryName.SantaElena,
    code: 'SH',
    phoneCode: '+290',
  },
  {
    name: CountryName.SantaLucia,
    code: 'LC',
    phoneCode: '+1758',
  },
  {
    name: CountryName.SantoTomeYPrincipe,
    code: 'ST',
    phoneCode: '+239',
  },
  {
    name: CountryName.Senegal,
    code: 'SN',
    phoneCode: '+221',
  },
  {
    name: CountryName.Serbia,
    code: 'RS',
    phoneCode: '+381',
  },
  {
    name: CountryName.Seychelles,
    code: 'SC',
    phoneCode: '+248',
  },
  {
    name: CountryName.SierraLeona,
    code: 'SL',
    phoneCode: '+232',
  },
  {
    name: CountryName.Singapur,
    code: 'SG',
    phoneCode: '+65',
  },
  {
    name: CountryName.Siria,
    code: 'SY',
    phoneCode: '+963',
  },
  {
    name: CountryName.Somalia,
    code: 'SO',
    phoneCode: '+252',
  },
  {
    name: CountryName.SriLanka,
    code: 'LK',
    phoneCode: '+94',
  },
  {
    name: CountryName.Sudafrica,
    code: 'ZA',
    phoneCode: '+27',
  },
  {
    name: CountryName.Sudan,
    code: 'SD',
    phoneCode: '+249',
  },
  {
    name: CountryName.Suecia,
    code: 'SE',
    phoneCode: '+46',
  },
  {
    name: CountryName.Suiza,
    code: 'CH',
    phoneCode: '+41',
  },
  {
    name: CountryName.Surinam,
    code: 'SR',
    phoneCode: '+597',
  },
  {
    name: CountryName.SvalbardYJanMayen,
    code: 'SJ',
    phoneCode: '+47',
  },
  {
    name: CountryName.Swazilandia,
    code: 'SZ',
    phoneCode: '+268',
  },
  {
    name: CountryName.Tailandia,
    code: 'TH',
    phoneCode: '+66',
  },
  {
    name: CountryName.Taiwan,
    code: 'TW',
    phoneCode: '+886',
  },
  {
    name: CountryName.Tanzania,
    code: 'TZ',
    phoneCode: '+255',
  },
  {
    name: CountryName.Tayikistan,
    code: 'TJ',
    phoneCode: '+992',
  },
  {
    name: CountryName.TerritorioBritanicoDelOceanoIndico,
    code: 'IO',
    phoneCode: '+246',
  },
  {
    name: CountryName.TimorOriental,
    code: 'TL',
    phoneCode: '+670',
  },
  {
    name: CountryName.Togo,
    code: 'TG',
    phoneCode: '+228',
  },
  {
    name: CountryName.Tokelau,
    code: 'TK',
    phoneCode: '+690',
  },
  {
    name: CountryName.Tonga,
    code: 'TO',
    phoneCode: '+676',
  },
  {
    name: CountryName.TrinidadYTobago,
    code: 'TT',
    phoneCode: '+1868',
  },
];
